# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiamCalc
                                 A QGIS plugin
 Umożliwia przeliczanie obwodów na średnice oraz średnic na obwody
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-10-07
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Łukasz Słowik
        email                : ---
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .diam_calc_dialog import DiamCalcDialog
import os.path

# LS
from qgis.core import QgsVectorLayer, QgsField
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QVariant
import time
from .obw_d import DiamCalculator
from .diam_calc_info import DlgInfo


class DiamCalc:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DiamCalc_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Przelicznik średnic i obwodów')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DiamCalc', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/diam_calc/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Przelicznik średnic i obwodów'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Przelicznik średnic i obwodów'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = DiamCalcDialog()
            
            # ADDED BY LS
            self.dlg.obw_in_dlg.fileChanged.connect(self.obw_in_changed)
            self.dlg.btn_box.accepted.connect(self.btn_box_accepted)
            self.dlg.btn_box.rejected.connect(self.btn_box_rejected)

        # show the dialog
        self.dlg.show()
#        result = self.dlg.exec_()
#        if result:
#            # Do something useful here - delete the line containing pass and
#            # substitute with your code.
#            obw_col_nm = self.dlg.obw_diam_cmb.currentText()
#            d_col_nm = self.dlg.obw_newcol_led.text()
#            sep_type = self.dlg.obw_sep_cmb.currentText()[-3:-2]
#            
#            DiamCalculator.obw_d_calc(self.lyr, obw_col_nm, d_col_nm, sep_type)
            
            
    # ADDED BY LS
    def obw_in_changed(self):
        if self.dlg.obw_in_dlg.filePath() == "":
            self.dlg.obw_diam_cmb.clear()
        else: 
            self.path = self.dlg.obw_in_dlg.filePath()
            self.lyr = QgsVectorLayer(self.path, "", "ogr")
            
            if self.lyr.isValid():
                col_lst = self.lyr.attributeAliases()
                
                self.dlg.obw_diam_cmb.clear()
                self.dlg.obw_diam_cmb.addItems(col_lst)
                
                index = self.dlg.obw_diam_cmb.findText("diam_tronc", QtCore.Qt.MatchFixedString)
                if index >= 0:
                    self.dlg.obw_diam_cmb.setCurrentIndex(index)


    def btn_box_accepted(self):
        if self.dlg.obw_in_dlg.filePath() == "":
            QMessageBox.warning(self.dlg, 'Błąd!', 'Nie wybrano pliku')
        elif not self.lyr.isValid():
            QMessageBox.warning(self.dlg, 'Błąd!', 'Błędny plik')
        elif self.dlg.obw_diam_cmb.currentText() =="":
            QMessageBox.warning(self.dlg,'Błąd!', 'Nie wybrano kolumny z obwodami')
        elif self.dlg.obw_newcol_led.text()=="":
            QMessageBox.warning(self.dlg,'Błąd!', 'Nie wybrano nazwy kolumny z średnicami')
        else:
            self.dlg_info = DlgInfo()
            self.dlg_info.setModal(True)
            
            self.dlg_info.info_ted.append('Obliczenia w trakcie, proszę czekać ...')
            
            self.dlg_info.timer = QtCore.QTimer()
            self.dlg_info.timer.setSingleShot(True)
            self.dlg_info.timer.setInterval(100)
            self.dlg_info.timer.timeout.connect(self.evt_timer_timeout)
            
            self.dlg_info.show()
            self.dlg_info.timer.start()
            self.dlg_info.exec_()
    
        
    def evt_timer_timeout(self):
        obw_col_nm = self.dlg.obw_diam_cmb.currentText()
        d_col_nm = self.dlg.obw_newcol_led.text()
        sep_type = self.dlg.obw_sep_cmb.currentText()[-3:-2]
        
        try:
            msg = DiamCalculator.obw_d_calc(self.lyr, obw_col_nm, d_col_nm, sep_type)
        except Exception as e:
            msg = f"Błąd! \n\n\
            - {repr(e)} \n\
            - Sprawdź poprawność danych \n\
            - Sprawdź czy wybrano właściwą kolumnę"

        self.dlg_info.info_ted.clear()
        self.dlg_info.info_ted.setText(f'{msg}')


    def btn_box_rejected(self):
        self.dlg.close()