# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiamCalc
                                 A QGIS plugin
 Umożliwia przeliczanie obwodów na średnice oraz średnic na obwody
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-07
        copyright            : (C) 2022 by Łukasz Słowik
        email                : ---
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DiamCalc class from file DiamCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .diam_calc import DiamCalc
    return DiamCalc(iface)
